from math import sin, cos, pi

print """# auto-generated by make_bends.py
define road_bend road_tile
(
  road
  ("""

num_blocks = 10

tile_size = 20.0
road_width = 6.0

rad_min = (tile_size-road_width)/tile_size

line_width = 0.2

rad_line_min = (tile_size-0.5*road_width-line_width)/tile_size
rad_line_max = (tile_size-0.5*road_width+line_width)/tile_size

for ii in range(num_blocks):
  th_min = ii*0.5*pi/num_blocks
  th_max = (ii+1.0)*0.5*pi/num_blocks
  # the road base
  print """  block
  (
  points 4"""
  print "  point[0] [%f %f]" % (sin(th_min),1-cos(th_min))
  print "  point[1] [%f %f]" % (sin(th_max),1-cos(th_max))
  print "  point[2] [%f %f]" % (rad_min*sin(th_max),(1-rad_min*cos(th_max)))
  print "  point[3] [%f %f]" % (rad_min*sin(th_min),(1-rad_min*cos(th_min)))
  print """  z [0 0.9]
  )"""

print ")"
